import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useAuth, useClerk } from "@clerk/nextjs";
import Link from "next/link";
import { useEffect, useState } from "react";

export default function Home() {
  const { getToken } = useAuth();
  const { signOut } = useClerk();

  const [token, setToken] = useState<string | null>(null);

  useEffect(() => {
    const fetchToken = async () => {
      const token = await getToken();

      setToken(token);
    };

    fetchToken();
  }, [getToken]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <button onClick={() => signOut()}>Sign out</button>
        <Link href={"/impersonate"}>Impersonate a User</Link>
      </main>
    </>
  );
}
